### PR TITLE
#36 (part 2) Added readme section about conditional recalculation

### PR DESCRIPTION
**Pull request by tjallingt**
https://github.com/foxbenjaminfox/vue-async-computed/pull/36#issuecomment-408491416

### CODE REVIEW

**Comment by tjallingt** [comment]
Made it a subsection of `Recalculation` (notice the extra #) since i figured it was quite related to watch...

**Comment by tjallingt** [comment]
did a small code cleanup when i was attempting to understand the effect of `shouldUpdate` on the `lazy` option (I don't really understand how lazy works so I have a hard time figuring out what the behaviour is)... just including it here, can revert if you don't like it

**Comment by tjallingt** [comment]
oh wait its merged already... mb i misunderstood

**Comment by foxbenjaminfox** [comment]
Yes, it's already merged.

If you're up for adding a new test case, we probably should have one that tests that `watch` and `shouldUpdate` both work when an async computed property has both.

**Pull request closed without merging**
