### PR TITLE
WIP: TypeScript typings

### LINKED ISSUE #25: Typescript
Any plans to add Typescript support?

Thanks.

### PR DESCRIPTION
**Pull request by saraedum**
resolves #25

### CODE REVIEW

**Comment by saraedum** [comment]
I am not a TypeScript expert but this works for me. Please let me know what you think and thanks for this very useful extension :)

**Comment by saraedum** [comment]
To try out these typings in your project, you can temporarily add
```
yarn add https://github.com/saraedum/vue-computed-async.git\#bf4f0aa766c59a63433b741a7f75ccdbd55b62a2
```
instead of vue-computed-async (or the corresponding NPM command.)

**Comment by trollderius** [comment]
asyncComputed property warning is solved but if I call an asyncComputed method from from other computed says: `Property 'xxx' does not exist on type 'CombinedVueInstance<Vue, { ...`
(vscode)

**Comment by saraedum** [comment]
@trollderius, you are right, that part is still missing. Let me see if I can get that to work as well.

**Comment by trollderius** [comment]
My workaround here is using an 'any' interface, but the sad thing is all types correlations are lost.
```
interface AsyncComputedObject {
  [K: string]: any;
}
```

`(this as AsyncComputedObject).xxx`

**Comment by trollderius** [comment]
Oh, in that case would be:
```
import { IAsyncComputedProperties } from 'xxx.d.js';
(this as IAsyncComputedProperties).xxx
```
And you need **export** `IAsyncComputedProperties` from index.d.ts
```
export interface IAsyncComputedProperties {
  [K: string]: AsyncComputedGetter<any> | IAsyncComputedProperty<any>;
}
```

**Comment by saraedum** [comment]
I am not sure whether it's possible to get the types right. My most promising attempt so far was
```
declare module "vue/types/options" {
	interface ComputedOptions<T> {
		asynchronous?: (() => T | Promise<T>) | {
			get: (() => T | Promise<T>);
			default?: T;
			lazy?: boolean;
		};
	}
}
```

With this I can set a computed's `asynchronous` such as
```
computed: {
  x: {
      asynchronous(): Promise<string> { return Promise.resolve(…) }
  }
}
```
and TypeScript knows that `this.x` is a string.

I got this to work mostly (strangely it does not work in `Vue.extend`.) However, there is no way to make `vue-property-decorator` work properly. I would have liked to be able to write a decorator such as
```
@asynchronous
get x() {
  return Promise.resolve(…);
}
```

However decorators in TypeScript can not modify the return type yet, so this did not work.

**Comment by saraedum** [comment]
So, I am not satisfied with the current state of this and I don't have more time to invest here.

**Pull request closed without merging**
